In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../Data/cleaned_dataset.csv")

df.head()

,house_number,name,phone_number,area,family_size,diet_type,meat_days,vegetables,fruits,food_grains,rice_type,dairy_products,rice_per_day,rice_per_month,milk_per_week,grocery_source,vegetable_frequency,grocery_frequency
0,201,p mahema sai,9739697840,doddakallasandra,4.0,Non_Vegetarian,wednesday;friday;sunday,onion;tomato;carrot;potato;beans;chilli,banana;apple;orange;grapes;watermelon;pomegranate,rice;millets;ragi;wheat,white rice;basmati;brown rice,milk;curd;panner;buttermilk;ice cream,0.5,6.0,5.0,metro,weekly once,Monthly
1,20,namitha n reddy,9108291205,koramangala,5.0,Vegetarian,not_applicable,onion;tomato;carrot;potato;beans;cabbage;drums...,banana;apple;orange;papaya;guava;kiwi,rice;millets;ragi;barley,white rice,milk;curd;panner,0.5,6.0,5.0,local kirana stores,Biweekly,Biweekly
2,703,n,9876512349,doddakallasandra,4.0,Vegetarian,not_applicable,tomato;carrot;potato;beans;chilli,banana;apple;orange;papaya;guava,rice;jawar;millets;wheat,white rice;sona masuri;idli/dosa rice;brown rice,milk;curd;panner;buttermilk;ice cream,0.5,6.0,3.0,blinkit,weekly twice,weekly once
3,251,shobhika santhosh,7022167063,hsr,3.0,Non_Vegetarian,wednesday;friday;saturday;sunday,onion;tomato;carrot;potato;brinjal;beans;cabba...,banana;apple;mango,rice;millets;ragi;wheat,red rice/rajamudi,milk;curd;panner;buttermilk;ice cream,0.5,3.0,1.0,lulu daily,weekly once,Biweekly
4,147,NaN,9513144130,vijayanagar,4.0,Eggetarian,not_applicable,onion;tomato;carrot;beans;cabbage,banana;apple;orange;papaya,rice;millets;wheat;maize,white rice;sona masuri;idli/dosa rice,milk;curd,0.5,6.0,7.0,amazon fresh;amazon now,weekly twice,Biweekly

In [3]:
print(df.shape)
print(df.columns)

(122, 18)
Index(['house_number', 'name', 'phone_number', 'area', 'family_size',
       'diet_type', 'meat_days', 'vegetables', 'fruits', 'food_grains',
       'rice_type', 'dairy_products', 'rice_per_day', 'rice_per_month',
       'milk_per_week', 'grocery_source', 'vegetable_frequency',
       'grocery_frequency'],
      dtype='object')

In [4]:
zone_mapping = {

    # =========================
    # SOUTH BANGALORE
    # =========================

    "hsr":"South",
    "koramangala":"South",
    "btm":"South",
    "jp nagar":"South",
    "jayanagar":"South",
    "banashankari":"South",
    "bannerghatta":"South",
    "bannerghatta road":"South",
    "electronic city":"South",
    "begur":"South",
    "isro layout":"South",
    "haralur":"South",
    "singasandra":"South",
    "arehalli":"South",
    "anjanapura":"South",
    "doddakallasandra":"South",
    "chandapura":"South",
    "uttarahalli":"South",
    "kaggalipura":"South",
    "kaglipura":"South",
    "gottigere":"South",
    "hulimavu":"South",
    "bommanahalli":"South",
    "hongasandra":"South",
    "akshayanagar":"South",
    "yelachenahalli":"South",
    "konanakunte":"South",
    "basavanagudi":"South",

    # =========================
    # EAST BANGALORE
    # =========================

    "whitefield":"East",
    "marathahalli":"East",
    "bellandur":"East",
    "mahadevapura":"East",
    "kr puram":"East",
    "kadugodi":"East",
    "brookefield":"East",
    "kundalahalli":"East",
    "kundapura":"East",
    "nagondanahalli":"East",
    "ramamurthy nagar":"East",
    "cv raman nagar":"East",
    "indiranagar":"East",
    "domlur":"East",
    "murugeshpalya":"East",
    "varthur":"East",
    "sarjapur":"East",
    "sarjapur road":"East",
    "g m palya":"East",
    "old airport road":"East",
    "doddanekkundi":"East",
    "kaggadasapura":"East",
    "aecs layout":"East",

    # =========================
    # NORTH BANGALORE
    # =========================

    "hebbal":"North",
    "anand nagar hebbal post":"North",
    "yelahanka":"North",
    "sahakarnagar":"North",
    "nagavara":"North",
    "rt nagar":"North",
    "vidyaranyapura":"North",
    "jakkur":"North",
    "thanisandra":"North",
    "manyata":"North",
    "hennur":"North",
    "hebbal kempapura":"North",
    "kodigehalli":"North",
    "kogilu":"North",
    "byatarayanapura":"North",
    "yeshwanthpur":"North",

    # =========================
    # WEST BANGALORE
    # =========================

    "vijayanagar":"West",
    "rajajinagar":"West",
    "rr nagar":"West",
    "rajarajeshwari nagar":"West",
    "kengeri":"West",
    "nagarbhavi":"West",
    "chandra layout":"West",
    "sunkadakatte":"West",
    "sunkadkatte":"West",
    "magadi road":"West",
    "basaveshwaranagar":"West",
    "basaveshwara nagar":"West",
    "kamakshipalya":"West",
    "mysore road":"West",
    "attiguppe":"West",
    "malleshwaram":"west",

    # =========================
    # CENTRAL BANGALORE
    # =========================

    "shivajinagar":"Central",
    "vasanth nagar":"Central",
    "vasanthanagar":"Central",
    "cubbon park":"Central",
    "richmond town":"Central",
    "mg road":"Central",
    "brigade road":"Central",
    "ulsoor":"Central",
    "frazer town":"Central",
    "cox town":"Central",
    "chamrajpet":"Central",
    "majestic":"Central",
    "gandhinagar":"Central",
    "andrahalli":"Central",

    "hanumanthnagar": "South",
    "r t nagar": "North",
    "vasanthnagar": "East",
    "srinagar": "South",
    "tavarekere": "South",
    "chandhapura": "South",
    "j p nagar": "South",
    "batrayanpura": "North",
    "r r nagar": "West",
    "nagadevanahalli": "West",
    "padrayanapura": "West",
    "nayandhalli": "West",
    "basaweshwarnagar": "West",
    "konanakunte cross": "South",
    "malleswaram": "West",
    "kormangala": "South",
    "jp nagar 8th phase": "South"
}

In [5]:
df["zone"] = df["area"].map(zone_mapping)

df[["area","zone"]].head()

               area   zone
0  doddakallasandra  South
1       koramangala  South
2  doddakallasandra  South
3               hsr  South
4       vijayanagar   West

In [6]:
print(df["zone"].isna().sum())

df[df["zone"].isna()][["area"]].drop_duplicates()

0

Empty DataFrame
Columns: [area]
Index: []

In [7]:
df["zone"] = df["area"].map(zone_mapping)

In [8]:
df["zone"].isna().sum()

0

In [9]:
missing_areas = sorted(df[df["zone"].isna()]["area"].unique())

print("Missing Areas:", len(missing_areas))
print(missing_areas)

Missing Areas: 0
[]

In [10]:
print(df.shape)
print(df["area"].nunique())

(122, 19)
48

In [11]:
df["zone"] = df["area"].map(zone_mapping)

In [12]:
df["rice_per_person"] = (
    df["rice_per_month"] /
    df["family_size"]
).round(2)

In [13]:
df["milk_per_person"] = (
    df["milk_per_week"] /
    df["family_size"]
).round(2)

In [14]:
df["vegetable_count"] = (
    df["vegetables"]
    .fillna("")
    .apply(lambda x: len(x.split(";")) if x else 0)
)

In [15]:
df["fruit_count"] = (
    df["fruits"]
    .fillna("")
    .apply(lambda x: len(x.split(";")) if x else 0)
)

In [16]:
df["grain_count"] = (
    df["food_grains"]
    .fillna("")
    .apply(lambda x: len(x.split(";")) if x else 0)
)

In [17]:
df["dairy_count"] = (
    df["dairy_products"]
    .fillna("")
    .apply(lambda x: len(x.split(";")) if x else 0)
)

In [18]:
df["store_count"] = (
    df["grocery_source"]
    .fillna("")
    .apply(lambda x: len(x.split(";")) if x else 0)
)

In [19]:
df[[
    "vegetable_count",
    "fruit_count",
    "grain_count",
    "dairy_count",
    "store_count"
]].head()

   vegetable_count  fruit_count  grain_count  dairy_count  store_count
0                6            6            4            5            1
1                7            6            4            3            1
2                5            5            4            5            1
3                8            3            4            5            1
4                5            4            4            2            2

In [20]:
vegetable_encoded = df["vegetables"].str.get_dummies(sep=";")

vegetable_encoded.columns = (
    "veg_" +
    vegetable_encoded.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
)


df = pd.concat([df, vegetable_encoded], axis=1)

df.drop(columns=["vegetables"], inplace=True)

print(f"Vegetable Features Created: {vegetable_encoded.shape[1]}")
vegetable_encoded.head()

Vegetable Features Created: 19

,veg_beans,"veg_bottle_gourd,",veg_bottle_guard,veg_brinjal,veg_cabbage,veg_carrot,veg_cauliflower,veg_chayote_squash,veg_chilli,veg_cucumber,veg_drumstick,veg_greens,veg_hagalkai,veg_okra,veg_onion,veg_peas,veg_potato,veg_tomato,veg_zukkini
0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1,1,0
1,1,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,1,1,0
2,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,1,0
3,1,0,0,1,1,1,0,0,1,0,0,0,0,0,1,0,1,1,0
4,1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,0

In [21]:
print(df.columns)

Index(['house_number', 'name', 'phone_number', 'area', 'family_size',
       'diet_type', 'meat_days', 'fruits', 'food_grains', 'rice_type',
       'dairy_products', 'rice_per_day', 'rice_per_month', 'milk_per_week',
       'grocery_source', 'vegetable_frequency', 'grocery_frequency', 'zone',
       'rice_per_person', 'milk_per_person', 'vegetable_count', 'fruit_count',
       'grain_count', 'dairy_count', 'store_count', 'veg_beans',
       'veg_bottle_gourd,', 'veg_bottle_guard', 'veg_brinjal', 'veg_cabbage',
       'veg_carrot', 'veg_cauliflower', 'veg_chayote_squash', 'veg_chilli',
       'veg_cucumber', 'veg_drumstick', 'veg_greens', 'veg_hagalkai',
       'veg_okra', 'veg_onion', 'veg_peas', 'veg_potato', 'veg_tomato',
       'veg_zukkini'],
      dtype='object')

In [22]:
fruits_encoded = df["fruits"].str.get_dummies(sep=";")

fruits_encoded.columns = (
    "fruits_" +
    fruits_encoded.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
)

df = pd.concat([df, fruits_encoded], axis=1)

df.drop(columns=["fruits"], inplace=True)
print(f"Fruits Features Created: {fruits_encoded.shape[1]}")
fruits_encoded.head()

Fruits Features Created: 20

,fruits_apple,fruits_banana,fruits_blue_berry,fruits_grapes,fruits_guava,fruits_jammun,fruits_kiwi,fruits_litchi,fruits_lychee,fruits_mango,fruits_mangos_during_season,fruits_muskmelon,fruits_orange,fruits_papaya,fruits_passionfruit,fruits_plum,fruits_plum_mango,fruits_pomegranate,fruits_strawberry,fruits_watermelon
0,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1
1,1,1,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0
2,1,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0

In [23]:
store_encoded = df["grocery_source"].str.get_dummies(sep=";")

store_encoded.columns = (
    "store_" +
    store_encoded.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
)

df = pd.concat([df, store_encoded], axis=1)

df.drop(columns=["grocery_source"], inplace=True)

In [24]:
dairy_encoded = df["dairy_products"].str.get_dummies(sep=";")

dairy_encoded.columns = (
    "dairy_" +
    dairy_encoded.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
)

df = pd.concat([df, dairy_encoded], axis=1)

df.drop(columns=["dairy_products"], inplace=True)

In [25]:
diet_encoded = pd.get_dummies(
    df["diet_type"],
    prefix="diet"
)

df = pd.concat([df, diet_encoded], axis=1)

df.drop(columns=["diet_type"], inplace=True)

In [26]:
rice_encoded = pd.get_dummies(
    df["rice_type"],
    prefix="rice"
)

df = pd.concat([df, rice_encoded], axis=1)

df.drop(columns=["rice_type"], inplace=True)

In [27]:
zone_encoded = pd.get_dummies(
    df["zone"],
    prefix="zone"
)

df = pd.concat([df, zone_encoded], axis=1)

df.drop(columns=["zone"], inplace=True)

In [28]:
grocery_freq_map = {
    "Weekly": 1,
    "Twice a Week": 2,
    "Biweekly": 3,
    "Monthly": 4
}

df["grocery_frequency"] = df["grocery_frequency"].map(grocery_freq_map)

In [29]:
veg_freq_map = {
    "Daily": 1,
    "Twice a Week": 2,
    "Weekly": 3,
    "Biweekly": 4,
    "Monthly": 5
}

df["vegetable_frequency"] = df["vegetable_frequency"].map(veg_freq_map)

In [30]:
print("="*50)
print("Dataset Shape")
print("="*50)

print(df.shape)

==================================================
Dataset Shape
==================================================
(122, 155)

In [31]:
print("="*50)
print("Missing Values")
print("="*50)

print(df.isnull().sum())

print("\nTotal Missing Values:", df.isnull().sum().sum())

==================================================
Missing Values
==================================================
house_number    0
name            4
phone_number    0
area            0
family_size     1
               ..
zone_Central    0
zone_East       0
zone_North      0
zone_South      0
zone_West       0
Length: 155, dtype: int64

Total Missing Values: 151

In [32]:
print("Vegetable Features :", len([c for c in df.columns if c.startswith("veg_")]))
print("Fruit Features     :", len([c for c in df.columns if c.startswith("fruit_")]))
print("Grain Features     :", len([c for c in df.columns if c.startswith("grain_")]))
print("Dairy Features     :", len([c for c in df.columns if c.startswith("dairy_")]))
print("Store Features     :", len([c for c in df.columns if c.startswith("store_")]))

Vegetable Features : 19
Fruit Features     : 1
Grain Features     : 1
Dairy Features     : 6
Store Features     : 23

In [33]:
display(df.head())

,house_number,name,phone_number,area,family_size,meat_days,food_grains,rice_per_day,rice_per_month,milk_per_week,...,rice_white rice;sona masuri;red rice/rajamudi,rice_white rice;sona masuri;red rice/rajamudi;basmati;brown rice,rice_white rice;sona masuri;red rice/rajamudi;basmati;idli/dosa rice,rice_white rice;sona masuri;red rice/rajamudi;idli/dosa rice,rice_white rice;sona masuri;red rice/rajamudi;idli/dosa rice;brown rice,zone_Central,zone_East,zone_North,zone_South,zone_West
0,201,p mahema sai,9739697840,doddakallasandra,4.0,wednesday;friday;sunday,rice;millets;ragi;wheat,0.5,6.0,5.0,...,False,False,False,False,False,False,False,False,True,False
1,20,namitha n reddy,9108291205,koramangala,5.0,not_applicable,rice;millets;ragi;barley,0.5,6.0,5.0,...,False,False,False,False,False,False,False,False,True,False
2,703,n,9876512349,doddakallasandra,4.0,not_applicable,rice;jawar;millets;wheat,0.5,6.0,3.0,...,False,False,False,False,False,False,False,False,True,False
3,251,shobhika santhosh,7022167063,hsr,3.0,wednesday;friday;saturday;sunday,rice;millets;ragi;wheat,0.5,3.0,1.0,...,False,False,False,False,False,False,False,False,True,False
4,147,NaN,9513144130,vijayanagar,4.0,not_applicable,rice;millets;wheat;maize,0.5,6.0,7.0,...,False,False,False,False,False,False,False,False,False,True

In [34]:
print("="*60)
print("FINAL FEATURE ENGINEERED DATASET")
print("="*60)

print(f"Rows           : {df.shape[0]}")
print(f"Columns        : {df.shape[1]}")
print(f"Missing Values : {df.isnull().sum().sum()}")
print(f"Duplicate Rows : {df.duplicated().sum()}")

print("\nPreview:")
display(df.head())

============================================================
FINAL FEATURE ENGINEERED DATASET
============================================================
Rows           : 122
Columns        : 155
Missing Values : 151
Duplicate Rows : 0

Preview:

,house_number,name,phone_number,area,family_size,meat_days,food_grains,rice_per_day,rice_per_month,milk_per_week,...,rice_white rice;sona masuri;red rice/rajamudi,rice_white rice;sona masuri;red rice/rajamudi;basmati;brown rice,rice_white rice;sona masuri;red rice/rajamudi;basmati;idli/dosa rice,rice_white rice;sona masuri;red rice/rajamudi;idli/dosa rice,rice_white rice;sona masuri;red rice/rajamudi;idli/dosa rice;brown rice,zone_Central,zone_East,zone_North,zone_South,zone_West
0,201,p mahema sai,9739697840,doddakallasandra,4.0,wednesday;friday;sunday,rice;millets;ragi;wheat,0.5,6.0,5.0,...,False,False,False,False,False,False,False,False,True,False
1,20,namitha n reddy,9108291205,koramangala,5.0,not_applicable,rice;millets;ragi;barley,0.5,6.0,5.0,...,False,False,False,False,False,False,False,False,True,False
2,703,n,9876512349,doddakallasandra,4.0,not_applicable,rice;jawar;millets;wheat,0.5,6.0,3.0,...,False,False,False,False,False,False,False,False,True,False
3,251,shobhika santhosh,7022167063,hsr,3.0,wednesday;friday;saturday;sunday,rice;millets;ragi;wheat,0.5,3.0,1.0,...,False,False,False,False,False,False,False,False,True,False
4,147,NaN,9513144130,vijayanagar,4.0,not_applicable,rice;millets;wheat;maize,0.5,6.0,7.0,...,False,False,False,False,False,False,False,False,False,True

In [35]:
binary_columns = [col for col in df.columns if col.startswith(("veg_", "fruit_", "grain_", "dairy_", "store_", "diet_", "rice_", "zone_", "family_"))]

invalid = []

for col in binary_columns:
    values = set(df[col].unique())
    if not values.issubset({0, 1, True, False}):
        invalid.append((col, values))

if invalid:
    print(" Non-binary encoded columns found:")
    for col, values in invalid:
        print(f"{col}: {values}")
else:
    print(" All encoded columns are binary.")

 Non-binary encoded columns found:
family_size: {1.0, 2.0, 3.0, 4.0, 5.0, 6.0, nan}
rice_per_day: {0.5, 1.0, 2.0, 1.5, 4.0, 3.0, 5.0, 0.2, 0.25, 0.75, nan}
rice_per_month: {3.0, 6.0, 10.0, 14.0, 18.0, 22.0}
rice_per_person: {0.75, 1.5, 2.5, 1.2, 1.0, 5.0, 3.0, 4.67, 3.6, 0.6, 1.67, 2.33, 3.5, 2.0, 6.0, 14.0, 3.33, 3.67, 4.5, 4.4, 5.5, nan, 2.8}
fruit_count: {1, 2, 3, 4, 5, 6, 7, 8}
grain_count: {1, 2, 3, 4, 5, 6, 7, 8, 9}
dairy_count: {1, 2, 3, 4, 5}
store_count: {1, 2, 3, 4, 5, 6, 8}

In [36]:
required_columns = [
    "family_size",
    "zone",
    "diet_type",          
    "rice_per_day",
    "rice_per_month",
    "milk_per_week"
]

for col in required_columns:
    print(f"{col}: {'yes' if col in df.columns else 'no'}")

family_size: yes
zone: no
diet_type: no
rice_per_day: yes
rice_per_month: yes
milk_per_week: yes

In [37]:
df[["food_grains"]].head(10)

                                         food_grains
0                            rice;millets;ragi;wheat
1                           rice;millets;ragi;barley
2                           rice;jawar;millets;wheat
3                            rice;millets;ragi;wheat
4                           rice;millets;wheat;maize
5                        rice;jawar;ragi;wheat;maize
6                                         rice;wheat
7                              rice;ragi;wheat;maize
8  rice;jawar;millets;ragi;wheat;maize;barley;sor...
9               rice;millets;ragi;wheat;maize;barley

In [38]:
print(df.columns[df.columns.str.startswith("grain_")])

Index(['grain_count'], dtype='object')

In [39]:
grain_encoded = df["food_grains"].fillna("").str.get_dummies(sep=";")


grain_encoded.columns = (
    "grain_" +
    grain_encoded.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
)

df = pd.concat([df, grain_encoded], axis=1)

df.drop(columns=["food_grains"], inplace=True)

In [40]:
df["vegetable_frequency"] = df["vegetable_frequency"].fillna(3)

In [41]:
df["grocery_frequency"] = df["grocery_frequency"].fillna(4)

In [42]:
df["family_size"] = df["family_size"].fillna(df["family_size"].median())

df["milk_per_person"] = df["milk_per_person"].fillna(df["milk_per_person"].median())

In [43]:
print(df.isnull().sum()[df.isnull().sum() > 0])

name               4
meat_days          7
rice_per_day       1
rice_per_person    1
dtype: int64

In [44]:
print(df.filter(regex="rice").columns.tolist())

['rice_per_day', 'rice_per_month', 'rice_per_person', 'rice_basmati', 'rice_basmati;idli/dosa rice', 'rice_black rice', 'rice_brown rice', 'rice_bullet rice', 'rice_jeerige sanna;basmati', 'rice_madhusanna;basmati;idli/dosa rice;brown rice', 'rice_madhusanna;red rice/rajamudi;idli/dosa rice;black rice', 'rice_madhusanna;red rice/rajamudi;idli/dosa rice;brown rice;black rice', 'rice_red rice/rajamudi', 'rice_red rice/rajamudi;idli/dosa rice;brown rice', 'rice_sona masuri', 'rice_sona masuri;', 'rice_sona masuri;basmati;idli/dosa rice;brown rice', 'rice_sona masuri;brown rice', 'rice_sona masuri;idli/dosa rice', 'rice_sona masuri;jeerige sanna', 'rice_sona masuri;jeerige sanna;basmati;idli/dosa rice', 'rice_sona masuri;jeerige sanna;idli/dosa rice', 'rice_sona masuri;jeerige sanna;idli/dosa rice;brown rice', 'rice_sona masuri;jeerige sanna;red rice/rajamudi;basmati;brown rice', 'rice_sona masuri;jeerige sanna;red rice/rajamudi;basmati;idli/dosa rice', 'rice_sona masuri;red rice/rajamudi', 'rice_sona masuri;red rice/rajamudi;basmati', 'rice_sona masuri;red rice/rajamudi;idli/dosa rice', 'rice_white rice', 'rice_white rice;basmati', 'rice_white rice;basmati;brown rice', 'rice_white rice;basmati;idli/dosa rice', 'rice_white rice;basmati;idli/dosa rice;brown rice', 'rice_white rice;brown rice', 'rice_white rice;idli/dosa rice', 'rice_white rice;idli/dosa rice;brown rice', 'rice_white rice;jeerige sanna', 'rice_white rice;jeerige sanna;basmati', 'rice_white rice;jeerige sanna;basmati;idli/dosa rice', 'rice_white rice;jeerige sanna;idli/dosa rice', 'rice_white rice;jeerige sanna;red rice/rajamudi;idli/dosa rice', 'rice_white rice;red rice/rajamudi', 'rice_white rice;red rice/rajamudi;basmati;idli/dosa rice', 'rice_white rice;red rice/rajamudi;basmati;idli/dosa rice;brown rice', 'rice_white rice;red rice/rajamudi;brown rice', 'rice_white rice;red rice/rajamudi;idli/dosa rice', 'rice_white rice;red rice/rajamudi;idli/dosa rice;brown rice', 'rice_white rice;sona masuri;basmati', 'rice_white rice;sona masuri;basmati;idli/dosa rice', 'rice_white rice;sona masuri;brown rice', 'rice_white rice;sona masuri;idli/dosa rice', 'rice_white rice;sona masuri;idli/dosa rice;brown rice', 'rice_white rice;sona masuri;jeerige sanna;idli/dosa rice', 'rice_white rice;sona masuri;madhusanna;brown rice;black rice', 'rice_white rice;sona masuri;madhusanna;jeerige sanna;red rice/rajamudi;basmati;idli/dosa rice;brown rice;black rice', 'rice_white rice;sona masuri;madhusanna;jeerige sanna;red rice/rajamudi;basmati;idli/dosa rice;brown rice;black rice;', 'rice_white rice;sona masuri;madhusanna;red rice/rajamudi;basmati', 'rice_white rice;sona masuri;red rice/rajamudi', 'rice_white rice;sona masuri;red rice/rajamudi;basmati;brown rice', 'rice_white rice;sona masuri;red rice/rajamudi;basmati;idli/dosa rice', 'rice_white rice;sona masuri;red rice/rajamudi;idli/dosa rice', 'rice_white rice;sona masuri;red rice/rajamudi;idli/dosa rice;brown rice', 'grain_rice']

In [68]:
print(df["rice_type"].head())

KeyError: 'rice_type'

In [67]:
rice_encoded = df["rice_type"].fillna("").str.get_dummies(sep=";")

rice_encoded.columns = (
    "rice_" +
    rice_encoded.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("/", "_", regex=False)
)

df = df.drop(columns=[c for c in df.columns if c.startswith("rice_")], errors="ignore")

df = pd.concat([df, rice_encoded], axis=1)

KeyError: 'rice_type'

In [52]:
print([c for c in df.columns if c.startswith("rice_")])

['rice_basmati', 'rice_black_rice', 'rice_brown_rice', 'rice_bullet_rice', 'rice_idli_dosa_rice', 'rice_jeerige_sanna', 'rice_madhusanna', 'rice_red_rice_rajamudi', 'rice_sona_masuri', 'rice_white_rice']

In [53]:
train_df = df.drop(
    columns=[
        "house_number",
        "name",
        "phone_number",
        "area"
    ],
    errors="ignore"
)

train_df.to_csv(
    "../Data/model_dataset.csv",
    index=False
)

In [54]:
df = pd.read_csv("../Data/featured_engineering_dataset.csv")

print("rice_per_month" in df.columns)

False

In [55]:
print(df.columns.tolist())

['house_number', 'name', 'phone_number', 'area', 'family_size', 'meat_days', 'milk_per_week', 'vegetable_frequency', 'grocery_frequency', 'milk_per_person', 'vegetable_count', 'fruit_count', 'grain_count', 'dairy_count', 'store_count', 'veg_beans', 'veg_bottle_gourd,', 'veg_bottle_guard', 'veg_brinjal', 'veg_cabbage', 'veg_carrot', 'veg_cauliflower', 'veg_chayote_squash', 'veg_chilli', 'veg_cucumber', 'veg_drumstick', 'veg_greens', 'veg_hagalkai', 'veg_okra', 'veg_onion', 'veg_peas', 'veg_potato', 'veg_tomato', 'veg_zukkini', 'fruits_apple', 'fruits_banana', 'fruits_blue_berry', 'fruits_grapes', 'fruits_guava', 'fruits_jammun', 'fruits_kiwi', 'fruits_litchi', 'fruits_lychee', 'fruits_mango', 'fruits_mangos_during_season', 'fruits_muskmelon', 'fruits_orange', 'fruits_papaya', 'fruits_passionfruit', 'fruits_plum', 'fruits_plum_mango', 'fruits_pomegranate', 'fruits_strawberry', 'fruits_watermelon', 'store_all_of_this', 'store_amazon_fresh', 'store_amazon_now', 'store_big_market', 'store_bigbasket', 'store_blinkit', 'store_dmart', 'store_dmart_ready', 'store_flipkart_minutes', 'store_from_our_coffee_estate', 'store_gandhi_bazaar', 'store_general_stores', 'store_jio_mart', 'store_k_r_market', 'store_local_kirana_stores', 'store_lulu_daily', 'store_metro', 'store_more_mega_store', 'store_reliance_fresh', 'store_shoprite_mall', 'store_swiggy_instamart', 'store_zepto', 'dairy_buttermilk', 'dairy_curd', 'dairy_ice_cream', 'dairy_milk', 'dairy_panner', 'diet_Eggetarian', 'diet_Non_Vegetarian', 'diet_Pescatarian', 'diet_Vegan', 'diet_Vegetarian', 'diet_jain', 'zone_Central', 'zone_East', 'zone_North', 'zone_South', 'zone_West', 'grain_barley', 'grain_jawar', 'grain_jowar', 'grain_maize', 'grain_millets', 'grain_ragi', 'grain_rice', 'grain_sorghum', 'grain_wheat', 'rice_basmati', 'rice_black_rice', 'rice_brown_rice', 'rice_bullet_rice', 'rice_idli_dosa_rice', 'rice_jeerige_sanna', 'rice_madhusanna', 'rice_red_rice_rajamudi', 'rice_sona_masuri', 'rice_white_rice']

In [60]:
clean_df = pd.read_csv("../Data/cleaned_dataset.csv")  

df["rice_per_month"] = clean_df["rice_per_month"]
df["rice_per_day"] = clean_df["rice_per_day"]
df["milk_per_week"] = clean_df["milk_per_week"]

df.to_csv("../Data/featured_engineering_dataset.csv", index=False)

In [61]:
df["rice_per_person"] = df["rice_per_month"] / df["family_size"]

In [62]:
df["rice_per_person"] = df["rice_per_month"] / df["family_size"].replace(0, 1)

In [63]:
df.to_csv("../Data/featured_engineering_dataset.csv", index=False)

In [64]:
print(df[["rice_per_day", "rice_per_month", "rice_per_person", "milk_per_week"]].head())

   rice_per_day  rice_per_month  rice_per_person  milk_per_week
0           0.5             6.0              1.5            5.0
1           0.5             6.0              1.2            5.0
2           0.5             6.0              1.5            3.0
3           0.5             3.0              1.0            1.0
4           0.5             6.0              1.5            7.0

In [65]:
df = pd.read_csv("../Data/featured_engineering_dataset.csv")
print("rice_per_month" in df.columns)

True